LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := OPWeather1
LOCAL_MODULE_STEM := OPWeather1.apk
LOCAL_SRC_FILES := OPWeather1.apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/app/OPWeather1

include $(BUILD_PREBUILT)
